Add an caution for the usage of path
walinejs/waline pull request #1535
Opened 2022-10-23 14:08 UTC by Likenttt

2022-10-23 14:11 UTC, lizheming approved these changes

2022-10-23 14:27 UTC, merged

2022-10-24 01:50 UTC, Mister-Hope commented
能解释一下例子2么

2022-10-24 02:08 UTC, Mister-Hope requested changes

2022-10-24 02:08 UTC, Mister-Hope commented on docs/src/reference/component.md
> +例子 2: 如果你想在站点的 `/en/path/` 和 `/path` 加载同样的评论，你最好将其设置为 `window.location.pathname.substring(3)`。
```suggestion
例子 2: 如果你想在站点的 `/en/path/` 和 `/path` 加载同样的评论，你最好将其设置为 `window.location.pathname.replace(/^\/en\//, '/')`。
```

2022-10-24 04:58 UTC, Likenttt commented on docs/src/reference/component.md
> +例子 2: 如果你想在站点的 `/en/path/` 和 `/path` 加载同样的评论，你最好将其设置为 `window.location.pathname.substring(3)`。
Well. `/en/path` -> `/path` 当然可以用replace, substring(3) 也没错

2022-10-24 04:59 UTC, Likenttt commented on docs/src/reference/component.md
> +例子 2: 如果你想在站点的 `/en/path/` 和 `/path` 加载同样的评论，你最好将其设置为 `window.location.pathname.substring(3)`。
although理解上不够直观

2022-10-24 05:56 UTC, Mister-Hope commented on docs/src/reference/component.md
> +例子 2: 如果你想在站点的 `/en/path/` 和 `/path` 加载同样的评论，你最好将其设置为 `window.location.pathname.substring(3)`。
那 `/path` 不是变成了 `th`? 我自始至终都觉得你这个会令人更迷惑。

2022-10-24 05:56 UTC, Mister-Hope commented on docs/src/reference/component.md
> +例子 2: 如果你想在站点的 `/en/path/` 和 `/path` 加载同样的评论，你最好将其设置为 `window.location.pathname.substring(3)`。
你要是说你在所有英文文章里手动 `window.location.pathname.substring(3)`，那跟手动敲一下结果有什么区别么？

2022-10-24 07:22 UTC, Likenttt commented on docs/src/reference/component.md
> +例子 2: 如果你想在站点的 `/en/path/` 和 `/path` 加载同样的评论，你最好将其设置为 `window.location.pathname.substring(3)`。
确实, 你的表述更加严谨且通用.