feat: Use Libravatar as default avatar (profile picture) provider
walinejs/waline pull request #481
Opened 2021-08-23 13:15 UTC by SakuragawaAsaba

Libravatar is a free, open-source avatar provider features federated hosting and Gravatar-compatible APIs. It also redirects to Gravatar automatically when no matching avatar exists in Libravatar.

2021-08-23 13:17 UTC, lizheming approved these changes

2021-08-23 13:26 UTC, Mister-Hope requested changes
Please update related docs.

2021-08-23 13:53 UTC, Mister-Hope commented
Dicusstion here, I am not familiar with llibravatar, what's the benifit for forerigners (mainly EU and US) switching from gravatar to libravatar? Cuz most foreign website are still using gravatar.

If there are more disadvantages than advatanages for those not inside GFW, maybe we should adjust en docs.

2021-08-23 13:55 UTC, Mister-Hope approved these changes

2021-08-23 13:57 UTC, Mister-Hope commented
Besides, maybe you should try to pass the linter test? We sure can add another commit to fix it, but it would be nice if it's not having any problems in this PR😉

2021-08-23 14:08 UTC, SakuragawaAsaba commented
Gravatar is a centralized avatar providers. It is a de-facto and easy-to-use. Yet it is not perfect, or at least it is not free (as in free will) or open-sourced.

Libravatar is free and supports self-hosting. When it is self-hosted, it uses a federation machanism which based on domain (SRV record on DNS), and you can run either ivatar (the same software as libravatar.org) or any other trusted solution that provides the same APIs. This enables you to fetch avatar by a unified method but keep the data on your own.

Regarding the aspect of compatibility, Libravatar uses the same API (URL schema) as Gravatar, and will fall back to Gravatar if no record in Libravatar matches the query. Using Libravatar as the default provider offers an (beneficial) alternative while keeping old users.

I have put some briefing about Libravatar in the documentation. Linters are complaining about that, but I am trying to comfort it.

2021-08-24 02:20 UTC, Mister-Hope commented
LGTM

2021-08-24 02:20 UTC, merged